CREATE DATABASE BMS_DB1;

USE BMS_DB1;
CREATE TABLE CUSTOMER_PERSONAL_INFO
( CUSTOMER_ID VARCHAR(5),
CUSTOMER_NAME VARCHAR(30),
DATE_OF_BIRTH DATE,
GUARDIAN_NAME VARCHAR(30),
ADDRESS VARCHAR(50),
CONTACT_NO BIGINT(10),
MAIL_ID VARCHAR(30),
GENDER CHAR(1),
MARITAL_STATUS VARCHAR(10),
IDENTIFICATION_DOC_TYPE VARCHAR(20),
ID_DOC_NO VARCHAR (20),
CITIZENSHIP VARCHAR(10),
CONSTRAINT CUST_PERS_INFO_PK PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE CUSTOMER_REFERENCE_INFO
(CUSTOMER_ID VARCHAR(5),
REFERENCE_ACC_NAME VARCHAR(20),
REFERENCE_ACC_NO BIGINT(16),
RELATION VARCHAR(25),
CONSTRAINT CUST_REF_INFO_PK PRIMARY KEY(CUSTOMER_ID),
CONSTRAINT CUST_REF_INFO_PK FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER_PERSONAL_INFO(CUSTOMER_ID)
);

CREATE TABLE BANK_INFO
( IFSC_CODE VARCHAR(15),
BANK_NAME VARCHAR(25),
BRANCH_NAME VARCHAR(25),
CONSTRAINT BANK_INFO_PK PRIMARY KEY(IFSC_CODE)
);

CREATE TABLE ACCOUNT_INFO
(ACCOUNT_NO BIGINT(16),
CUSTOMER_ID VARCHAR(5),
ACCOUNT_TYPE VARCHAR(10),
REGISTRATION_DATE DATE,
ACTIVATION_DATE DATE,
IFSC_CODE VARCHAR(10),
INTERST DECIMAL(7,2),
INITIAL_DEPOSIT BIGINT(10),
PRIMARY KEY(ACCOUNT_NO),
FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER_PERSONAL_INFO(CUSTOMER_ID),
FOREIGN KEY (IFSC_CODE) references BANK_INFO(BRANCH_NAME)
);
INSERT INTO BANK_INFO (IFSC_CODE,BANK_NAME,BRANCH_NAME) VALUES ('HVDL2024' , 'SBI' , 'PATULIA');
INSERT INTO BANK_INFO (IFSC_CODE,BANK_NAME,BRANCH_NAME) VALUES ('HVDL2025' , 'HDFC' , 'KHARDAHA');
INSERT INTO BANK_INFO (IFSC_CODE,BANK_NAME,BRANCH_NAME) VALUES ('HVDL2021' , 'ICICI' , 'RAHARA');
INSERT INTO BANK_INFO (IFSC_CODE,BANK_NAME,BRANCH_NAME) VALUES ('HVDL2022' , 'SBI' , 'PATULIA');
INSERT INTO BANK_INFO (IFSC_CODE,BANK_NAME,BRANCH_NAME) VALUES ('HVDL2023' , 'SBI' , 'PATULIA');

INSERT INTO CUSTOMER_PERSONAL_INFO (CUSTOMER_ID,CUSTOMER_NAME,DATE_OF_BIRTH,GUARDIAN_NAME,ADDRESS, CONTACT_NO,MAIL_ID,GENDER,MARITAL_STATUS,IDENTIFICATION_DOC_TYPE,ID_DOC_NO,CITIZENSHIP)
VALUES('1001','ARITRA', '1999-11-23' , 'ASHOK', 'KOLKATA', '123' , 'ADRI','M', 'NO', '1234Q' , 1234 , 'INDIA');

INSERT INTO CUSTOMER_PERSONAL_INFO (CUSTOMER_ID,CUSTOMER_NAME,DATE_OF_BIRTH,GUARDIAN_NAME,ADDRESS, CONTACT_NO,MAIL_ID,GENDER,MARITAL_STATUS,IDENTIFICATION_DOC_TYPE,ID_DOC_NO,CITIZENSHIP)
VALUES('1002','ARITRA', '1999-11-23' , 'ASHOK', 'KOLKATA', '123' , 'ADRI','M', 'NO', '1234Q' , 1234 , 'INDIA');


INSERT INTO CUSTOMER_PERSONAL_INFO (CUSTOMER_ID,CUSTOMER_NAME,DATE_OF_BIRTH,GUARDIAN_NAME,ADDRESS, CONTACT_NO,MAIL_ID,GENDER,MARITAL_STATUS,IDENTIFICATION_DOC_TYPE,ID_DOC_NO,CITIZENSHIP)
VALUES('1003','ARITRA', '1999-11-23' , 'ASHOK', 'KOLKATA', '123' , 'ADRI','M', 'NO', '1234Q' , 1234 , 'INDIA');


INSERT INTO CUSTOMER_PERSONAL_INFO (CUSTOMER_ID,CUSTOMER_NAME,DATE_OF_BIRTH,GUARDIAN_NAME,ADDRESS, CONTACT_NO,MAIL_ID,GENDER,MARITAL_STATUS,IDENTIFICATION_DOC_TYPE,ID_DOC_NO,CITIZENSHIP)
VALUES('1004','ARITRA', '1999-11-23' , 'ASHOK', 'KOLKATA', '123' , 'ADRI','M', 'NO', '1234Q' , 1234 , 'INDIA');











